allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    
    // Provide flutter properties to plugins that expect them
    ext {
        flutterCompileSdkVersion = 34
        flutterMinSdkVersion = 23
        flutterTargetSdkVersion = 34
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
